
# This is an example wexe application configuration file.
# Since this is named "example.toml", it configures an app stub named
# "example.exe" in the same directory.

# The target executable file path. This is outside any named section,
# so must come first
target = "C:\\bin\\example.exe"

# This section allows prepending and appending additional command line
# arguments to ones passed to the wexe loader executable.
[args]
prepend = [ "arg1", "arg2" ]
append = [ "arg98", "arg99" ]

# This is the top level environment variables section.
# It has some subsections below but only directly contains
# some subcommands that don't take a key+value.
[env]
# Delete the "BAR" and "BAZ" environment variables, if they exist
delete = [ 
  "BAR",
  "BAZ",
]

# This is the environment variables override / add subsection.
[env.set]
# Set the "FOO" environment variable to "bar" (overriding it or setting it).
FOO = "bar"

# This section has subsections for appending and prepending to path-like
# environment variables. It doesn't directly contain any key+value pairs.
[env.pathlike]

# This is the path-like environment variables prepend/append section for "PATH".
# (the last segment, "PATH", is the name of the environment variable to edit)
[env.pathlike.PATH]
# Prepend the following paths to the "PATH" environment variable.
# Note that the path of the target executable is automatically prepended.
prepend = [
  ".",
]
# Append the following paths to the "PATH" environment variable.
append = [
  "C:\\Windows\\System32",
  "C:\\bin",
]

